### ISSUE TITLE
Cannot find module 'electron-updater'

### ISSUE THREAD

**Issue by cedkim** [geschafft-co/puddle#4]
When I open Puddle, this error message shows up.

![](https://i.ibb.co/b3Rwh19/Puddle-Error-1.png)

**Comment by probonopd** [comment]
Similar on Linux:

Throws exception:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-updater'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/run/firejail/appimage/.appimage-10336/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10336/resources/app.asar/src/main.js:4:23)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10336/resources/app.asar/src/main.js:43:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
Xlib:  extension "RANDR" missing on display ":99".
/proc/self/exe: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /proc/self/exe)
(node:4) UnhandledPromiseRejectionWarning: Error: Not supported
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10336/resources/app.asar/src/main.js:3:12)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10336/resources/app.asar/src/main.js:43:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10336/resources/electron.asar/browser/init.js:188:8)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10336/resources/electron.asar/browser/init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/1341

**Comment by cedkim** [comment]
78f0b381b7ca55f38b821a0391fdd9b5dafc03ac should fix things. I'll test it.

**Comment by cedkim** [comment]
It didn't work.

**Comment by cedkim** [comment]
I found the issue: I added `electron-updater` under `devDependencies` when it was supposed to be added under `dependencies`. (2691346ac6a0588f06a624a64505c35b957ab991)
But now, Puddle just shows a blank window.
